name: Build and Commit to Canary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: canary  # Specify the environment

    permissions:
      contents: write  # Grant write permission to the contents scope

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    - name: Import GPG key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Commit and push to canary branch
      run: |
        export GPG_TTY=$(tty)
        git config --global user.name '${{ secrets.GPG_USER_NAME }}'
        git config --global user.email '${{ secrets.GPG_USER_EMAIL }}'
        git config --global commit.gpgSign true
        git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}
        echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --import
        git checkout main
        git checkout -B canary
        git add -f frontend/dist
        git commit -S -m "Update canary with latest build from main"
        git push origin canary --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_USER_NAME: ${{ secrets.GPG_USER_NAME }}
        GPG_USER_EMAIL: ${{ secrets.GPG_USER_EMAIL }}
